language: python
python:
  - "2.7"
  - "3.5"

services:
  - postgresql

before_script:
  - psql -c "create database imagerDB;" -U postgres
  - imagersite/manage.py migrate

# command to install dependencies
install:
  - pip install -r requirements.pip
  - pip install coveralls
# command to run tests
script: 
  - coverage run imagersite/manage.py test

after_success:
  - coveralls